version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      npm-minor-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: "uv"
    directory: "/patilu-api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      python-minor-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: "docker"
    directory: "/patilu-web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      web-container-minor-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: "docker"
    directory: "/patilu-cms"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      cms-container-minor-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: "docker"
    directory: "/patilu-api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      api-container-minor-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      actions-minor-patch:
        update-types: ["minor", "patch"]
